### ISSUE TITLE
add image on last section

### ISSUE THREAD

**Issue by FritzHsiao** [mac-gallagher/MultiProgressView#13]
hi
Thanks for this fantastic library. 
I'm trying to add image view on the last section at specific position.
Is there any way to do that? Thanks

**Comment by mac-gallagher** [comment]
Since the `ProgressViewSection`s are just `UIView`s, you should just be able to add a subview to them directly. This is probably easiest done by first subclassing `ProgressViewSection`. Let me know if that works!
