### ISSUE TITLE
Unable to subclass in storyboard

### ISSUE THREAD

**Issue by angelinec** [mac-gallagher/MultiProgressView#17]
Hi Mac,

I bumped into an issue of subclassing MultiProgressView via storyboard.

Log shows this error :

<img width="753" alt="Screenshot 2019-04-01 at 2 42 10 PM" src="https://user-images.githubusercontent.com/9972417/55309006-02783680-548f-11e9-9913-efae50875d49.png">

And when I looked through **MultiProgressView.swift** , I found this

<img width="512" alt="Screenshot 2019-04-01 at 3 12 00 PM" src="https://user-images.githubusercontent.com/9972417/55309550-be863100-5490-11e9-8bd7-d0000c10638d.png">

Am I supposed to initialize something on my side?

MultiProgressView 1.0.2
Xcode version 10.1 (10B61)

p.s. Thanks for making this nice library! :)

**Comment by angelinec** [comment]
Never mind, saw it in the To-Do list. Closing this.

Thanks

**Comment by mac-gallagher** [comment]
Hi @angelinec,

Sorry there isn't storyboard support at the moment! That is the next item on my agenda for this repo :)

**Comment by mac-gallagher** [comment]
Hi @angelinec, storyboards should now work with version 1.1.0! Let me know if you run into any more issues!
