### ISSUE TITLE
section clickable 

### ISSUE THREAD

**Issue by mouness2020** [mac-gallagher/MultiProgressView#36]
Hello,, i want to know if you can implement section click delegate?

**Comment by mac-gallagher** [comment]
You should be able to just add a tap gesture to each section since they are subclasses of `UIView`. Did you try this?

**Comment by mouness2020** [comment]
ok i will try .. but if the library included this feature will be good.
Thanks

**Comment by mac-gallagher** [comment]
Added in [version 1.3.0](https://github.com/mac-gallagher/MultiProgressView/releases/tag/v1.3.0).
