### ISSUE TITLE
can u add percentage label (value) on each view 

### ISSUE THREAD

**Issue by AMM001** [mac-gallagher/MultiProgressView#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mac-gallagher** [comment]
This can be achieved by subclassing `ProgressViewSection` and adding your label there.

You can return your custom section in `progressView(_ progressView: MultiProgressView, viewForSection section: Int) -> ProgressViewSection`
