### ISSUE TITLE
“Ambiguous use of 'cornerRadius'” in Xcode 11, Swift 4.2

### ISSUE THREAD

**Issue by AMM001** [mac-gallagher/MultiProgressView#41]
Ambiguous use of 'cornerRadius'

**Comment by mac-gallagher** [comment]
The requirements state **Swift 5.0+** on the README

**Comment by AMM001** [comment]
hi  mac-gallagher , this issue. (“Ambiguous use of 'cornerRadius'”) in swift 5.0 also  

see that : https://github.com/AssistoLab/DropDown/issues/192 

the same issue , can u update your pod ?

**Comment by mac-gallagher** [comment]
@AMM001  Please create a new issue using the issue template and provide an example code snippet and I will look into it
