### ISSUE TITLE
 (“Ambiguous use of 'cornerRadius'”) in swift 5.0

### ISSUE THREAD

**Issue by AMM001** [mac-gallagher/MultiProgressView#43]
<img width="946" alt="Screen Shot 2020-05-04 at 10 40 18 AM" src="https://user-images.githubusercontent.com/26631632/80949264-f8440c80-8df3-11ea-88e9-284a14a822d4.png">

**Comment by erwang01** [comment]
Are there more details you can provide @AMM001 ? Its hard to debug 8 lines of code in a screen shot.

Also, does the Storage Example build properly for you? The use of .cornerRadius is used there too. (StorageExampleViewController.swift:25)

**Comment by mac-gallagher** [comment]
@AMM001 do you have an extension of `UIView` with a `cornerRadius` property on it? That would cause this issue

**Comment by mac-gallagher** [comment]
If not, it is also possible that you are importing another framework along with `MultiProgressView` with such an extension

**Comment by AMM001** [comment]
@mac-gallagher  yes in my project I have an extension of UIView with a cornerRadius 

but I can not change it cause a lot of views in project used it :( ! 

are u have any solution of this please 
thank u .

**Comment by mac-gallagher** [comment]
@AMM001 you can just rename your property to something unique like `cornerRadius_` and do the following:

```swift
extension UIView {

    var cornerRadius_: CGFloat {
        set {
            layer.cornerRadius = newValue
        }
        get {
            return layer.cornerRadius
       }
    }
}
```

Let me know if that works

**Comment by AMM001** [comment]
@mac-gallagher I don't like to change in extension , can u find a another solution with no change in property in extension . 

just look at this : https://github.com/AssistoLab/DropDown/issues/192#issuecomment-424259662 

thanks

**Comment by mac-gallagher** [comment]
@AMM001 Alternatively, you can extend `MultiProgressView` somewhere in your project:

```swift
import MultiProgressView

extension MultiProgressView {

  var mpv_cornerRadius: CGFloat {
    get {
      return super.cornerRadius
    }
    set {
      super.cornerRadius = newValue
    }
  }
}
```

(The call to `super.cornerRadius` here would reference the `cornerRadius` property defined in `Shuffle` and not the one in your project.) You can then do

```swift
let progressView = MultiProgressView()
progressView.mpv_cornerRadius
```

Does this work? I would rather not make any direct changes to the repo for your specific case.

**Comment by AMM001** [comment]
@mac-gallagher this solution doesn't work , I'm sorry for this 

the view doesn't take a corner radius

**Comment by mac-gallagher** [comment]
I just tried adding the `UIView` and `MultiProgressView` extensions defined above into the example project and it worked fine. Can you share more details? Perhaps a sample project?

**Comment by mac-gallagher** [comment]
Actually nevermind, it complied but did not have the desired effect.

In any case, this is not an issue with the repo but rather an issue with your naming convention. If you also add a similar `UIView` extension for `borderWidth` or `borderColor` for example, you will run into the same "Ambiguous use of ..." error. This is not the fault of the framework, so closing this issue.
