### ISSUE TITLE
Upgrade Nimble version to 9.0

### ISSUE THREAD

**Issue by jessemx109** [mac-gallagher/MultiProgressView#51]
**Is your feature request related to a problem? Please describe.**
While trying to integrate MultiProgressView via Swift package manager I am getting a collision on Nimble versions, specifically with Auth0 who has upgraded to Nimble 9.0

**Describe the solution you'd like**
Can you migrate the Nimble usage to 9.0 to unblock importing with other libraries that are using Nimble 9.0

**Comment by jessemx109** [comment]
@mac-gallagher Any updates on this? I am blocked from moving to SPM because of this issue

**Comment by mac-gallagher** [comment]
@jessemx109 I'm pretty sure this is a limitation of using SPM. What is the specific error you're seeing? 

To unblock yourself, why not create a fork of this repo and bump the version there? Bumping the version here may create new collisions for others. Right now we do not need 9.0, hence I see no reason to update

**Comment by jessemx109** [comment]
This is the error I am receiving. Auth0 has upgraded to 9.0 so spm cant resolve this package with the Auth0 package. I can fork the repo but was hoping to avoid that if i could so i wouldn't be tasked with managing back porting new versions to my fork. If you don't want to upgrade to Nimble 9.0 I can do down that route though

![Screen Shot 2021-04-30 at 4 34 15 PM](https://user-images.githubusercontent.com/1411012/116763213-ef1f5880-a9d1-11eb-9cbf-b85e893cbdde.png)

**Comment by mac-gallagher** [comment]
Thanks for sharing the error. Let's leave the Nimble version as-is for now. Reason is, while you have a project which needs Nimble to be >=9.0, others may have a project which depends on the version to be what it is now. 

As far as back-porting new versions of MultiProgressView goes, this repo isn't really under active development. If the current iteration of MultiProgressView works for you right now, you should be fine

**Comment by jessemx109** [comment]
@mac-gallagher the Auth0 swift repository just pushed out an update to omit the testing dependencies from spm, seems like a good solution to this problem. You can see the changes they made here

https://github.com/auth0/Auth0.swift/pull/476

**Comment by mac-gallagher** [comment]
Nice! Thanks for the update here @jessemx109. I will consider following the same solution
